#pragma once

const char WEB_UI_HTML[] PROGMEM = R"HTML(
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Smart Desk Clock</title><style>
:root{color-scheme:dark;--bg:#0d0f14;--panel:#13161f;--border:#252b3b;--text:#cdd6f4;--muted:#7c8499;--cyan:#00c8ff;--green:#00ff9d;--yellow:#f9e2af;--red:#f38ba8}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.wrap{max-width:860px;margin:auto;padding:18px}.head{display:flex;gap:12px;align-items:center;justify-content:space-between;margin-bottom:14px}.title{font-size:22px;font-weight:800}.pill{border:1px solid var(--border);padding:7px 10px;border-radius:99px;color:var(--muted)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.card{background:var(--panel);border:1px solid var(--border);border-radius:13px;padding:15px}.card h2{font-size:14px;color:var(--cyan);margin:0 0 14px}.wide{grid-column:1/-1}label{font-size:12px;color:var(--muted);display:block;margin:8px 0 5px}input,select{width:100%;background:#0b0d12;color:var(--text);border:1px solid var(--border);border-radius:8px;padding:10px}button{border:0;border-radius:8px;padding:10px 13px;font-weight:800;cursor:pointer;background:var(--cyan);color:#071015;margin-top:10px}button.alt{background:var(--green)}button.warn{background:var(--yellow)}button.danger{background:var(--red)}button.ghost{background:#232838;color:var(--text)}.row{display:flex;gap:8px;flex-wrap:wrap}.status{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.metric{background:#0b0d12;border:1px solid var(--border);padding:10px;border-radius:9px}.metric b{display:block;font-size:11px;color:var(--muted);margin-bottom:5px}.metric span{font-size:13px}.imgbox{display:grid;grid-template-columns:120px 1fr;gap:12px;align-items:center}.preview{width:103px;height:120px;object-fit:cover;background:#090b10;border:1px solid var(--border);border-radius:7px}.msg{min-height:20px;color:var(--green);margin-top:10px;font-size:12px}.hint{font-size:11px;color:var(--muted);line-height:1.55}.dangerzone{border-color:#5d2836}.dangerzone h2{color:var(--red)}@media(max-width:680px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.status{grid-template-columns:1fr 1fr}.imgbox{grid-template-columns:1fr}.head{align-items:flex-start;flex-direction:column}}
</style></head><body><div class="wrap"><div class="head"><div class="title">◈ SMART DESK CLOCK</div><div class="pill" id="clock">--:--:--</div></div>
<div class="card wide"><h2>DEVICE STATUS</h2><div class="status"><div class="metric"><b>Wi-Fi</b><span id="wifi">...</span></div><div class="metric"><b>STA IP</b><span id="ip">...</span></div><div class="metric"><b>Setup AP</b><span id="apip">192.168.4.1</span></div><div class="metric"><b>Timezone</b><span id="tzNow">...</span></div><div class="metric"><b>ESP Clock</b><span id="espTime">--:--:--</span></div></div></div>
<div class="grid">
<div class="card"><h2>NETWORK</h2><label>SSID</label><input id="ssid" autocomplete="off"><label>Password</label><input id="pass" type="password" placeholder="Leave blank to keep saved password"><button onclick="saveWifi()">Save & Connect</button><div class="hint">The setup access point stays available even if router connection fails.</div></div>
<div class="card"><h2>REGION & TIME</h2><label>Region</label><select id="region"></select><div class="row"><button class="alt" onclick="saveRegion()">Save Region & Sync</button><button class="ghost" onclick="syncNow()">Sync Now</button></div><div class="hint" id="preview"></div></div>
<div class="card"><h2>IMAGE 1</h2><div class="imgbox"><img class="preview" id="p1"><div><input id="f1" type="file" accept="image/*"><button class="warn" onclick="uploadImage(1)">Upload Image 1</button><button class="ghost" onclick="deleteImage(1)">Delete</button><div class="hint" id="i1"></div></div></div></div>
<div class="card"><h2>IMAGE 2</h2><div class="imgbox"><img class="preview" id="p2"><div><input id="f2" type="file" accept="image/*"><button class="warn" onclick="uploadImage(2)">Upload Image 2</button><button class="ghost" onclick="deleteImage(2)">Delete</button><div class="hint" id="i2"></div></div></div></div>
<div class="card wide dangerzone"><h2>DEVICE MAINTENANCE</h2><div class="row"><button class="ghost" onclick="restartEsp()">Restart ESP</button><button class="danger" onclick="eraseStorage()">Erase Flash Storage</button></div><div class="hint">Erase Flash Storage deletes saved Wi-Fi/timezone preferences and both SPIFFS images, then restarts the ESP.</div></div>
</div><div class="msg" id="msg"></div></div>
<script>
const REGIONS=[['Iran','Asia/Tehran','UTC+3:30'],['Germany','Europe/Berlin','UTC+1'],['United States (NY)','America/New_York','UTC-5'],['United Kingdom','Europe/London','UTC+0'],['Turkey','Europe/Istanbul','UTC+3'],['UAE','Asia/Dubai','UTC+4'],['Saudi Arabia','Asia/Riyadh','UTC+3'],['India','Asia/Kolkata','UTC+5:30'],['China','Asia/Shanghai','UTC+8'],['Japan','Asia/Tokyo','UTC+9'],['Russia (Moscow)','Europe/Moscow','UTC+3'],['Pakistan','Asia/Karachi','UTC+5'],['Iraq','Asia/Baghdad','UTC+3']];
const $=id=>document.getElementById(id);function message(s,bad=false){$('msg').style.color=bad?'var(--red)':'var(--green)';$('msg').textContent=s}async function req(url,opt={}){let r=await fetch(url,opt);let t=await r.text();if(!r.ok)throw Error(t||('HTTP '+r.status));try{return JSON.parse(t)}catch{return t}}
function fillRegions(){for(const r of REGIONS){let o=document.createElement('option');o.value=r[1];o.dataset.label=r[2];o.textContent=r[0]+' · '+r[1]+' · '+r[2];$('region').appendChild(o)}$('region').onchange=previewRegion;previewRegion()}
function previewRegion(){let r=REGIONS.find(x=>x[1]===$('region').value)||REGIONS[0];try{$('preview').textContent='Local browser preview: '+new Intl.DateTimeFormat([], {timeZone:r[1],hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())+' · '+r[2]}catch{$('preview').textContent=r[1]+' · '+r[2]}}
async function refresh(){try{let s=await req('/api/status');$('wifi').textContent=s.wifi_connected?('Connected · '+s.ssid):'Not connected';$('ip').textContent=s.sta_ip||'—';$('apip').textContent=s.ap_ip||'192.168.4.1';$('tzNow').textContent=s.timezone;$('espTime').textContent=s.time||'--:--:--';$('ssid').value=s.ssid||'';$('region').value=s.timezone;if(!$('region').value)$('region').value='Asia/Tehran';previewRegion();for(let n=1;n<=2;n++){let ok=s['img'+n];$('i'+n).textContent=ok?'Stored in flash':'No image stored';$('p'+n).src=ok?('/image/'+n+'?v='+Date.now()):''}}catch(e){message('Status error: '+e.message,true)}}
async function saveWifi(){let body=new URLSearchParams({ssid:$('ssid').value,password:$('pass').value});try{message('Connecting...');let x=await req('/api/wifi',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});message(x.message||'Wi-Fi updated');$('pass').value='';setTimeout(refresh,800)}catch(e){message(e.message,true)}}
function zonedParts(tz){let p=new Intl.DateTimeFormat('en-GB',{timeZone:tz,hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date());let g=t=>p.find(x=>x.type===t)?.value||'0';return {hour:g('hour'),minute:g('minute'),second:g('second')}}async function saveRegion(){let o=$('region').selectedOptions[0],z=zonedParts($('region').value);let body=new URLSearchParams({timezone:$('region').value,label:o.dataset.label||'',...z});try{let x=await req('/api/timezone',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});message(x.message||'Region saved');refresh()}catch(e){message(e.message,true)}}
async function syncNow(){try{let x=await req('/api/sync',{method:'POST'});message(x.message||'Time synced');refresh()}catch(e){message(e.message,true)}}
async function encode(file){let bmp=await createImageBitmap(file);let c=document.createElement('canvas');c.width=240;c.height=280;let x=c.getContext('2d');x.save();x.translate(0,280);x.scale(1,-1);x.drawImage(bmp,0,0,240,280);x.restore();let d=x.getImageData(0,0,240,280);for(let i=0;i<d.data.length;i+=4){let r=d.data[i];d.data[i]=d.data[i+2];d.data[i+2]=r}x.putImageData(d,0,0);return await new Promise(res=>c.toBlob(res,'image/jpeg',.75))}
async function uploadImage(n){let f=$('f'+n).files[0];if(!f){message('Choose image '+n+' first.',true);return}try{message('Encoding and uploading image '+n+'...');let b=await encode(f);let fd=new FormData();fd.append('image',b,'img'+n+'.jpg');let x=await req('/api/image/'+n,{method:'POST',body:fd});message(x.message||'Image uploaded');refresh()}catch(e){message(e.message,true)}}
async function deleteImage(n){if(!confirm('Delete image '+n+' from ESP flash?'))return;try{await req('/api/image/'+n,{method:'DELETE'});message('Image '+n+' deleted');refresh()}catch(e){message(e.message,true)}}
async function restartEsp(){if(!confirm('Restart ESP now?'))return;try{await req('/api/restart',{method:'POST'});message('Restart command sent. Reconnect in a moment.')}catch(e){message('Restart command sent.')}}
async function eraseStorage(){if(!confirm('WARNING: This deletes Wi-Fi credentials, timezone settings, and both images. Continue?'))return;if(!confirm('Final confirmation: erase ESP flash storage and restart?'))return;try{await req('/api/erase-storage',{method:'POST'});message('Storage erased. Connect to the setup AP again after restart.')}catch(e){message('Erase/restart command sent.')}}
fillRegions();refresh();setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString();previewRegion()},1000);setInterval(refresh,10000);
</script></body></html>
)HTML";
